export const CREATE_MAINCATEGORY = "CREATE_MAINCATEGORY";
export const CREATE_MAINCATEGORY_RED = "CREATE_MAINCATEGORY_RED";
export const CREATE_MAINCATEGORY_FAIL = "CREATE_MAINCATEGORY_FAIL";

export const UPDATE_MAINCATEGORY = "UPDATE_MAINCATEGORY";
export const UPDATE_MAINCATEGORY_RED = "UPDATE_MAINCATEGORY_RED";
export const UPDATE_MAINCATEGORY_FAIL = "UPDATE_MAINCATEGORY_FAIL"; // ✅ ADD

export const GET_MAINCATEGORY = "GET_MAINCATEGORY";
export const GET_MAINCATEGORY_RED = "GET_MAINCATEGORY_RED";

export const DELETE_MAINCATEGORY = "DELETE_MAINCATEGORY";
export const DELETE_MAINCATEGORY_SUCCESS = "DELETE_MAINCATEGORY_SUCCESS"; // ✅ ADD
export const DELETE_MAINCATEGORY_FAIL = "DELETE_MAINCATEGORY_FAIL";       // ✅ ADD
export const RESET_MAINCATEGORY_STATUS = "RESET_MAINCATEGORY_STATUS";

export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";
export const CREATE_SUBCATEGORY_RED = "CREATE_SUBCATEGORY_RED";
export const CREATE_SUBCATEGORY_FAIL = "CREATE_SUBCATEGORY_FAIL"
export const UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORY";
export const UPDATE_SUBCATEGORY_RED = "UPDATE_SUBCATEGORY_RED";
export const UPDATE_SUBCATEGORY_FAIL = "UPDATE_SUBCATEGORY_FAIL";
export const GET_SUBCATEGORY = "GET_SUBCATEGORY";
export const GET_SUBCATEGORY_RED = "GET_SUBCATEGORY_RED";
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY";
export const DELETE_SUBCATEGORY_RED = "DELETE_SUBCATEGORY_RED";
export const DELETE_SUBCATEGORY_SUCCESS = "DELETE_SUBCATEGORY_SUCCESS";
export const DELETE_SUBCATEGORY_FAIL = "DELETE_SUBCATEGORY_FAIL";
export const RESET_SUBCATEGORY_STATUS = "RESET_SUBCATEGORY_STATUS";

export const CREATE_BRAND = "CREATE_BRAND";
export const CREATE_BRAND_RED = "CREATE_BRAND_RED";
export const CREATE_BRAND_FAIL = "CREATE_BRAND_FAIL";
export const UPDATE_BRAND = "UPDATE_BRAND";
export const UPDATE_BRAND_RED = "UPDATE_BRAND_RED";
export const UPDATE_BRAND_FAIL = "UPDATE_BRAND_FAIL";
export const GET_BRAND = "GET_BRAND";
export const GET_BRAND_RED = "GET_BRAND_RED";
export const DELETE_BRAND = "DELETE_BRAND";
export const DELETE_BRAND_RED = "DELETE_BRAND_RED";
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS";
export const DELETE_BRAND_FAIL = "DELETE_BRAND_FAIL";
export const RESET_BRAND_STATUS = "RESET_BRAND_STATUS";


export const CREATE_FEATURE = "CREATE_FEATURE";
export const CREATE_FEATURE_RED = "CREATE_FEATURE_RED";
export const CREATE_FEATURE_FAIL = "CREATE_FEATURE_FAIL";
export const UPDATE_FEATURE = "UPDATE_FEATURE";
export const UPDATE_FEATURE_RED = "UPDATE_FEATURE_RED";
export const UPDATE_FEATURE_FAIL = "UPDATE_FEATURE_FAIL";
export const GET_FEATURE = "GET_FEATURE";
export const GET_FEATURE_RED = "GET_FEATURE_RED";
export const GET_FEATURE_FAIL = "GET_FEATURE_FAIL";
export const DELETE_FEATURE = "DELETE_FEATURE";
export const DELETE_FEATURE_RED = "DELETE_FEATURE_RED";
export const DELETE_FEATURE_FAIL = "DELETE_FEATURE_FAIL";
export const RESET_FEATURE_STATUS = "RESET_FEATURE_STATUS"

export const CREATE_FAQ = "CREATE_FAQ";
export const CREATE_FAQ_RED = "CREATE_FAQ_RED";
export const CREATE_FAQ_FAIL = "CREATE_FAQ_FAIL";
export const UPDATE_FAQ = "UPDATE_FAQ";
export const UPDATE_FAQ_RED = "UPDATE_FAQ_RED";
export const UPDATE_FAQ_FAIL = "UPDATE_FAQ_FAIL";
export const GET_FAQ = "GET_FAQ";
export const GET_FAQ_RED = "GET_FAQ_RED";
export const GET_FAQ_FAIL = "GET_FAQ_FAIL";
export const DELETE_FAQ = "DELETE_FAQ";
export const DELETE_FAQ_RED = "DELETE_FAQ_RED";
export const DELETE_FAQ_FAIL = "DELETE_FAQ_FAIL";
export const RESET_FAQ_STATUS = "RESET_FAQ_STATUS"

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_RED = "CREATE_PRODUCT_RED";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_RED = "UPDATE_PRODUCT_RED";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_RED = "GET_PRODUCT_RED";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_RED = "DELETE_PRODUCT_RED";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const RESET_PRODUCT_STATUS = "RESET_PRODUCT_STATUS"

export const UPDATE_USERS = "UPDATE_USERS";
export const UPDATE_USERS_RED = "UPDATE_USERS_RED";
export const UPDATE_USERS_FAIL = "UPDATE_USERS_FAIL";
export const GET_USERS = "GET_USERS";
export const GET_USERS_RED = "GET_USERS_RED";

export const CREATE_SETTING = "CREATE_SETTING";
export const CREATE_SETTING_RED = "CREATE_SETTING_RED";
export const UPDATE_SETTING = "UPDATE_SETTING";
export const UPDATE_SETTING_RED = "UPDATE_SETTING_RED";
export const GET_SETTING = "GET_SETTING";
export const GET_SETTING_RED = "GET_SETTING_RED";
export const DELETE_SETTING = "DELETE_SETTING";
export const DELETE_SETTING_RED = "DELETE_SETTING_RED";

export const CREATE_CART = "CREATE_CART";
export const CREATE_CART_RED = "CREATE_CART_RED";
export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_CART_FAIL = "UPDATE_CART_FAIL";
export const UPDATE_CART_RED = "UPDATE_CART_RED";
export const GET_CART = "GET_CART";
export const GET_CART_RED = "GET_CART_RED";
export const GET_CART_FAIL = "GET_CART_FAIL";
export const DELETE_CART = "DELETE_CART";
export const DELETE_CART_FAIL = "DELETE_CART_FAIL";
export const DELETE_CART_RED = "DELETE_CART_RED";

export const CREATE_WISHLIST = "CREATE_WISHLIST";
export const CREATE_WISHLIST_RED = "CREATE_WISHLIST_RED";
export const CREATE_WISHLIST_FAIL = "CREATE_WISHLIST_FAIL"
export const UPDATE_WISHLIST = "UPDATE_WISHLIST";
export const UPDATE_WISHLIST_RED = "UPDATE_WISHLIST_RED";
export const UPDATE_WISHLIST_FAIL = "UPDATE_WISHLIST_FAIL";
export const GET_WISHLIST = "GET_WISHLIST";
export const GET_WISHLIST_RED = "GET_WISHLIST_RED";
export const DELETE_WISHLIST = "DELETE_WISHLIST";
export const DELETE_WISHLIST_RED = "DELETE_WISHLIST_RED";
export const DELETE_WISHLIST_SUCCESS = "DELETE_WISHLIST_SUCCESS"
export const DELETE_WISHLIST_FAIL = "DELETE_WISHLIST_FAIL";

export const CREATE_ADDRESS = "CREATE_ADDRESS";
export const CREATE_ADDRESS_RED = "CREATE_ADDRESS_RED";
export const CREATE_ADDRESS_FAIL = "CREATE_ADDRESS_FAIL"
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const UPDATE_ADDRESS_RED = "UPDATE_ADDRESS_RED";
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL";
export const GET_ADDRESS = "GET_ADDRESS";
export const GET_ADDRESS_FAIL = "GET_ADDRESS_FAIL";
export const GET_ADDRESS_RED = "GET_ADDRESS_RED";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const DELETE_ADDRESS_RED = "DELETE_ADDRESS_RED";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS"
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL";


export const CREATE_CHECKOUT = "CREATE_CHECKOUT";
export const CREATE_CHECKOUT_FAIL = "CREATE_CHECKOUT_FAIL";
export const CREATE_CHECKOUT_RED = "CREATE_CHECKOUT_RED";
export const UPDATE_CHECKOUT = "UPDATE_CHECKOUT";
export const UPDATE_CHECKOUT_RED = "UPDATE_CHECKOUT_RED";
export const GET_CHECKOUT = "GET_CHECKOUT";
export const GET_CHECKOUT_FAIL = "GET_CHECKOUT_FAIL";
export const GET_CHECKOUT_RED = "GET_CHECKOUT_RED";
export const DELETE_CHECKOUT = "DELETE_CHECKOUT";
export const DELETE_CHECKOUT_RED = "DELETE_CHECKOUT_RED";
export const DELETE_CHECKOUT_FAIL = "DELETE_CHECKOUT_FAIL";

export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL";
export const CREATE_TESTIMONIAL_RED = "CREATE_TESTIMONIAL_RED";
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL";
export const UPDATE_TESTIMONIAL_RED = "UPDATE_TESTIMONIAL_RED";
export const GET_TESTIMONIAL = "GET_TESTIMONIAL";
export const GET_TESTIMONIAL_RED = "GET_TESTIMONIAL_RED";
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL";
export const DELETE_TESTIMONIAL_RED = "DELETE_TESTIMONIAL_RED";

